version: '3.4'
services:
  db:
    image: edualpendre/mysql-rest-with-spring-udemy
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: udemy_rest_spring
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  rest-with-spring-udemy:
    image: edualpendre/rest-with-spring-udemy
    restart: always
    build: ./RestWithSpringUdemy
    working_dir: /RestWithSpringUdemy
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./RestWithSpringUdemy:/RestWithSpringUdemy
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
    udemy-network:
        driver: bridge